with-expecter: true
packages:
  github.com/JoshuaPangaribuan/clean-arch-ddd/internal/domain/product:
    interfaces:
      ProductRepository:
        config:
          dir: "mocks"
          filename: "ProductRepository.go"
          package: "mocks"

